apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: phonebook
  name: mysql-db-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: phonebook
      tier: mysql
  strategy: 
    type: Recreate
  template: 
    metadata: 
      labels: 
        app: phonebook
        tier: mysql
    spec: 
      containers: 
        - 
          env: 
            - 
              name: MYSQL_DATABASE
              valueFrom: 
                configMapKeyRef: 
                  key: mysql-database
                  name: db
            - 
              name: MYSQL_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  key: rootpassword
                  name: mysql-secret
            - 
              name: MYSQL_USER
              valueFrom: 
                secretKeyRef: 
                  key: username
                  name: mysql-secret
            - 
              name: MYSQL_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  key: password
                  name: mysql-secret
          image: "mysql:5.7"
          name: mysql
          ports: 
            - 
              containerPort: 3306
              name: mysql
          volumeMounts: 
            - 
              mountPath: /var/lib/mysql
              name: mysql-persistent-storage
      volumes: 
        - 
          name: mysql-persistent-storage
          persistentVolumeClaim: 
            claimName: database-persistent-volume-claim
--- 
apiVersion: v1
kind: Service
metadata:
  name: mysql-db-service
  labels:
    name: mysql
    app: phonebook
spec:
  selector:
    name: mysql
  type: ClusterIP
  ports:
    - name: db
      port: 3306
      targetPort: 3306