apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: resultserver
    app: phonebookweb
spec:
  selector:
    name: resultserver 
  type: NodePort
  ports:
   - name: http
     port: 80
     targetPort: 80
     nodePort: 30002
     protocol: TCP