apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels: 
    app: resultserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultserver
  template:
    metadata:
      labels:
        app: resultserver
    spec:
      containers: 
      - image: pehlivan/result-phonebook
        imagePullPolicy: IfNotPresent
        name: resultserver
        ports: 
          - containerPort: 80
        env:
          - name: "MYSQL_DATABASE_HOST"
            value: mysql-service
          - name: "MYSQL_DATABASE"
            valueFrom: 
              configMapKeyRef: 
                key: mysql-database
                name: db 
          - name: "MYSQL_USER"
            valueFrom: 
              secretKeyRef: 
                key: username
                name: mysql-secret
          - name: "MYSQL_PASSWORD"
            valueFrom: 
              secretKeyRef: 
                key: password
                name: mysql-secret       