apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    name: webserver
    app: phonebookweb
spec:
  selector:
    name: webserver 
  type: NodePort
  ports:
   - name: http
     port: 80
     targetPort: 80
     nodePort: 30001
     protocol: TCP