apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webserver
  template:
    metadata:
      labels:
        name: webserver
        app: phonebookweb
    spec:
      containers: 
        image: pehlivan/mysql-phonebook
          imagePullPolicy: Never
          name: webserver
          ports: 
            - containerPort: 80
          env:
            - name: "MYSQL_DATABASE_HOST"
              value: mysql-db-service
            - name: "MYSQL_DATABASE"
              valueFrom: 
                configMapKeyRef: 
                  key: mysql-database
                  name: db 
            - name: "MYSQL_USER"
              valueFrom: 
                secretKeyRef: 
                  key: username
                  name: mysql-secret
            - name: "MYSQL_PASSWORD"
              valueFrom: 
                secretKeyRef: 
                  key: password
                  name: mysql-secret           